---
title: "On-Farm Precision Experiments"
---
The On-Farm Precision Experiments Framework was developed at Montana State University in 2015. Please refer to the [OFPE]() website for more information. This webpage contains technical information about the OFPE framework and data process and assumes the reader has a familiarity with the project. A cursory explantion is below.

## On-Farm Precision Experiments Framework
OFPE was initially funded by the Montana Research and Economic Development Initiative and continues to be funded by the Montana Fertilizer Advisory Committee and the Data Intensive Farm Management project at the University of Illinois to begin the process of creating an automated on-field experimentation system.

Research over the past 20 years has consistently indicated that crop response to inputs like fertilizers and herbicides are site specific in nature. Every field is different and most years are different. Therefore the OFPE takes advantage of modern technologies to conduct automated experiments on  each field that will optimize the use of field-specific inputs based on maximizing farmer profits. The data stream available to agricultural producers can be captured by algorithms that manage data and automates the process of conducting experiments, field by field. Farm managers can build or join a database where each farm and field's data can be stored for incorporation into the OFPE data pipeline, resulting in the simulation of a range of economic and climate futures, providing a basis for management under uncertainty and assessment of resilience.



